nginx:
    build: ../gifr-nginx
    image: gifr-nginx
    links:
        - node:node
    ports:
        - "80:80"
node:
    build: ../gifr-node
    image: gifr-node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        - ../gifr-node:/src
redis:
    build: ../gifr-redis
    image: gifr-redis
    ports:
        - "6379"
