nginx:
    build: ../gifr-nginx
    links:
        - node
    ports:
        - "8443:8443"
node:
    build: ../gifr-node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        - ../gifr-node:/src
redis:
    build: ../gifr-redis
    ports:
        - "6379"
